module.exports = {
	action: {
		SET_BAG_OPTION: "SET_BAG_OPTION",
		TOGGLE_PALETTE: "TOGGLE_PALETTE",
		TOGGLE_SIZECHOOSER: "TOGGLE_SIZECHOOSER",
		UPDATE_CUSTOMER_COMMENT: "UPDATE_CUSTOMER_COMMENT",
		UPDATE_BAGDATA: "UPDATE_BAGDATA",
		UPDATE_CUSTOMER_NAME: "UPDATE_CUSTOMER_NAME",
		RESET_BAGOPTION: "RESET_BAGOPTION",
		SET_DIALOG: "SET_DIALOG"
	}
};
