module.exports = {
	action: {
		GET_NEWS_LIST: "GET_NEWS_LIST",
		GET_DRIVERS_LIST: "GET_DRIVERS_LIST",
		GET_DRIVER_DETAIL: "GET_DRIVER_DETAIL",
		GET_DRIVER_COMPARE: "GET_DRIVER_COMPARE",
		FILTER: "FILTER",
		CLEAR_LIST: "CLEAR_LIST",
		GET_CALENDAR_LIST: "GET_CALENDAR_LIST",
		SAVE_FITLER: "SAVE_FITLER",
		LOADING_STATUS: "LOADING_STATUS",
		GET_ARTICLE: "GET_ARTICLE",
		GET_SUGGESTION: "GET_SUGGESTION",
		LOGIN: "LOGIN",
		ALERT_STATUS: "ALERT_STATUS",
		LOGOUT: "LOGOUT",
		FORGOT_PASSWORD: "FORGOT_PASSWORD",
		POST_FORM: "POST_FORM",
		MODIFY_META: "MODIFY_META"
	}
};
